= Frontend app

This simple frontend applications displays a web interface to send messages to a processing backend.

This app is written in Ruby using link:http://www.sinatrarb.com[the Sinatra framework].
The frontend use link:http://jquery.com[jQuery] and link:http://getbootstrap.com[Bootstrap].

The application should be compatible with Ruby MRI and JRuby.

The application connects to:

- link:http://zeromq.org[ZeroMQ] to send monitoring messages on port 2200
- link:http://redis.io[Redis] to send messages to the backend on port 6379 using the `app_queue` key

== Installation

- you need ZeroMQ on your system to install the libraries
- in the application's directory run `bundle install`

== Start the app

- Redis must be up and running to start the application
- in the application's directory run `rackup`
- open your browser at link:http://localhost:9292/[http://localhost:9292/]

=== Configuration

Configuration is done through environment variables:

- `APP_REDIS_PORT`: the Redis port used to send message to the backend, default is `6379`
- `APP_REDIS_KEY`: the Redis key used to send message to the backend, default is `app_queue`
- `MONITORING_ZMQ_PORT`: the ZeroMQ port to send monitoring messages, default is `2200`

=== Structure

- `lib/app_base.rb`: base for a frontend Sinatra application with redis messages
- `lib/monitoring_base.rb`: adds monitoring-related features
- `lib/frontend_app.rb`: the business code
- `static/index.html`: the frontend page

== License

Code (C) 2015 released under the MIT license