= Frontend app

This simple frontend applications displays a web interface and call REST services on a middle end.

This app is written in Ruby using link:http://www.sinatrarb.com[the Sinatra framework].
The frontend use link:http://jquery.com[jQuery] and link:http://getbootstrap.com[Bootstrap].

The application should be compatible with link:https://www.ruby-lang.org[Ruby] and link:http://jruby.org[JRuby].

The application connects to:

- link:http://zeromq.org[ZeroMQ] to send monitoring messages on port 2200
- the middle end application on port 8086

== Installation

- You need bundler gem install on your system (sudo gem install bundler)
- you need ZeroMQ on your system to install the libraries
- in the application's directory run `bundle install`

== Start the app

- in the application's directory run `rackup`
- open your browser at link:http://localhost:9292/[http://localhost:9292/]

=== Configuration

Configuration is done through environment variables:

- `MIDDLE_END_PORT`: the port to call the middle end services on, default is `8086`
- `MONITORING_ZMQ_PORT`: the ZeroMQ port to send monitoring messages, default is `2200`

=== Structure

- `lib/app_base.rb`: base for a frontend Sinatra application with Redis messages
- `lib/monitoring_base.rb`: adds monitoring-related features
- `lib/frontend_app.rb`: the business code
- `static/index.html`: the frontend page

== License

Code (C) 2015 released under the MIT license
