- name: install build depends
  apt: pkg={{ item }} state=present install_recommends=no
  with_items:
    - build-essential
    - git
    - libcurl4-openssl-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
  sudo: true

- name: checkout rbenv_repo
  git: >
    repo={{ rbenv_repo }}
    dest={{ rbenv_root }}
    version={{ rbenv.version }}
    accept_hostkey=true
  sudo: true

- name: create plugins directory
  file: state=directory path={{ rbenv_root }}/plugins
  sudo: true

- name: install plugins
  git: >
    repo={{ item.repo }}
    dest={{ rbenv_root }}/plugins/{{ item.name }}
    version={{ item.version }}
    accept_hostkey=true
  with_items: "{{ rbenv_plugins }}"
  sudo: true

- name: add rbenv initialization to profile
  template: src=rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755
  sudo: true

- name: check ruby {{ rbenv.ruby_version }} installed
  shell: bash -lc "rbenv versions | grep {{ rbenv.ruby_version }}"
  register: ruby_installed
  ignore_errors: yes

- name: install ruby {{ rbenv.ruby_version }}
  shell: bash -lc "rbenv install {{ rbenv.ruby_version }}"
  when: ruby_installed.rc != 0

- name: configure ruby {{ rbenv.ruby_version }}
  shell: bash -lc "rbenv global {{ rbenv.ruby_version }} && rbenv rehash"
  when: ruby_installed.rc != 0


