= Monitoring and CEP Application

This applications read audit messages from ZeroMQ and push them to elastic search

This app is written in Java 8 and relies on link:http://maven.apache.org[Maven] and link:http://camel.apache.org/[Apache Camel]

The application connects to:
- link:http://zeromq.org[ZeroMQ] to receive monitoring messages on ports `2200`,`2201`,`2202`
- link:http://www.elasticsearch.org[Elasticsearch] to push all the messages

The configuration can be changed in the application's `pom.xml` and in it's parent `pom.xml`.

== Installation

- Build all maven modules by running `mvn install` on the project's root
- Create the `monitoring` index in Elasticsearch `curl -XPUT 'http://localhost:9200/monitoring/'`

== Start the app

- ElasticSearch must be up and running
- You must have installed "monitoring-flux-shared" once in your local repository
- In the application's directory run `mvn hawtio:camel` or `mvn camel:run` if you don't want the console

== License

Code (C) 2015 released under the MIT license
