= ZeroMQ to Elasticsearch

This app is written in Ruby.

It fetch all the messages send to link:http://zeromq.org[ZeroMQ] and put them in link:http://www.elasticsearch.org[Elasticsearch].

The application should be compatible with Ruby MRI and JRuby.

== Installation

- you need ZeroMQ on your system to install the libraries
- in the application's directory run `bundle install`

== Start the app

- Elasticsearch must be up and running to start the application
- in the application's directory run `ruby zeromq_to_elasticsearch XXXX` where `XXXX` is the port number,

- `2200` is the default for the frontend app
- `2201` is the default for the middle end app.
- `2202` is the default for the backend app.

=== Configuration

Configuration is done through environment variables:

- `ELASTICSEARCH_PORT`: the Elasticsearch port, default is `9300`
- `ELASTICSEARCH_INDEX`: the Elasticsearch index where the data are inserted, default is `monitoring`

== License

Code (C) 2015 released under the MIT license